### ISSUE TITLE
how to get all output images when running ./raycasting in build

### ISSUE THREAD

**Issue by zheyuanlin** [dilevin/computer-graphics-ray-casting#10]
When I run ./raycasting in my build directory, I am only seeing 3 output images (the same as the ones in output_images/sphere-and-plane/.

How do I run my program so that it produces the rest of the output images? The images for inside-a-sphere, sphere-packing, two-spheres-and-plane, and triangle are not outputted when I run ./raycasting

**Comment by MNRKhan** [comment]
Run:
`./raycasting <.json file path for camera & scene description>`

Example:
`./raycasting ../shared/data/inside-a-sphere.json`
