### ISSUE TITLE
Camera doesn't get read properly from json

### ISSUE THREAD

**Issue by alexei-zolotarevschi** [dilevin/computer-graphics-ray-casting#11]
I tried making the contents of my viewing_ray.cpp just
`cout << camera.e << endl << endl;`
and it prints <-9.25596e+61, -9.25596e+61, -9.25596e+61> (seems like garbage data instead of <0, 0, 5>)
I did notice that the path it tries to read from in main.cpp is "../shared/data/sphere-and-plane.json", while my .json file is at "./shared/data/sphere-and-plane.json". Changing the path inside main.cpp doesn't work either. 
If this helps at all, my executable file appears in "build/Debug" instead of just "build". I'm guessing I'm doing something wrong with the setup, but there were no issues with A1.

Edit: I also get a few warnings for read_json.h when building the solution. Not sure if they are relevant:
```
read_json.h(8): warning C4099: 'Object': type name first seen using 'class' now seen using 'struct'
Object.h(8): note: see declaration of 'Object'
read_json.h(118): warning C4018: '<': signed/unsigned mismatch
read_json.h(122): warning C4244: 'argument': conversion from 'double' to 'const unsigned int', possible loss of data
read_json.h(123): warning C4244: 'argument': conversion from 'double' to 'const unsigned int', possible loss of data
read_json.h(124): warning C4244: 'argument': conversion from 'double' to 'const unsigned int', possible loss of data
```

**Comment by dilevin** [comment]
What platform and development environment are you using to build the assignment ?

**Comment by alexei-zolotarevschi** [comment]
Actually I think I got it. I was specifying the path to the json file with respect to main.cpp instead of the executable. Which was actually a level deeper than the default path. Sorry about that. I guess if the warnings aren't anything serious, this can be closed. Now I feel bad for wasting your time.

**Comment by dilevin** [comment]
No problem, glad you got it figured out.
