### ISSUE TITLE
TriangleSoup - Incorrect Bunny-Normal output

### ISSUE THREAD

**Issue by Geetchopra** [dilevin/computer-graphics-ray-casting#15]
I am not able to get the correct output for the normal picture for bunny.json. My triangle.cpp's normal calculation is correct since my output for triangle.json is correct. All other outputs also work, including bunny-id and bunny-depth. The algorithm I'm using is simply finding the first triangle hit in the soup and then intersecting the ray with that triangle.

This is my output image - 
<img width="642" alt="screen shot 2019-01-24 at 19 21 48" src="https://user-images.githubusercontent.com/12212222/51717056-51c46580-200d-11e9-8e5c-d940929bd952.png">

What could I be doing wrong?

**Comment by jritch** [comment]
My first reaction would be to make sure that you're actually setting the n parameter in TriangleSoup::intersect, using the value that you get from the inner call to Triangle::intersect.

**Comment by dilevin** [comment]
Do your other, non-bunny, normal images display correctly ?

**Comment by Geetchopra** [comment]
@jritch If I pass the n from TriangleSoup::intersect to the call of Triangle::intersect, wouldn't it be the same value since we have a call by reference to n everywhere?
I did explicitly assign n also but it didn't help.

**Comment by MNRKhan** [comment]
The grey color value (around 127,127,128 RGB) is being produced by a normal of 0 vector. Maybe double check if you are normalizing the normal vector properly (you can use `n.normalized()` among other ways).
