### ISSUE TITLE
Will you be running our code using a release build?

### ISSUE THREAD

**Issue by bod11** [dilevin/computer-graphics-ray-casting#18]
It says it should take a few seconds if you aren't using the release version. Mine takes about 5-6 seconds to compute the bunny using release, but it takes minutes when not using a release build. Is this a problem or typical? I don't feel like I am doing any intense un-needed computations in my current code XD.

**Comment by bod11** [comment]
Specifically, the way I am using Eigen to solve system of equations seems to be REALLY slow when not using a release build. Is algorithm optimisation a major consideration when grading?

**Comment by dilevin** [comment]
"the way I am using Eigen to solve system of equations seems to be REALLY slow"
You are not responsible for Eigen's performance.

**Comment by jritch** [comment]
I will compile and run with release when marking this assignment. If it doesn't work with the release build I will check with the debug build*. 

If the algorithm is correct you will still receive full marks if it works with either build.

*I can't guarantee that this will be the case for all assignments
