### ISSUE TITLE
Computing viewing rays

### ISSUE THREAD

**Issue by RaihanFaruque** [dilevin/computer-graphics-ray-casting#19]
In chapter 4 of the book, they try to fit nx × ny pixels into a rectangle of size (r − l) × (t − b).
But in the code we arn't given r,l,t, or b. Does this mean (r-l) = nx and (t-b) = ny ? 
Can we also assume that l = -r = nx ?

**Comment by darren-moore** [comment]
Indeed, the starter code assumes that `l = -r` and `b = -t`, so a width and height suffice to define our picture plane. This is the assumption in the lecture slides.

Also, we must be careful with which coordinate system we're working in. `(r-l) = width`, not `n_x`. Remember that `n_x` is the number of pixels on the screen, unrelated to the picture plane's size in space.

**Comment by RaihanFaruque** [comment]
On the viewing_ray.h file, it says:
//   width  number of pixels width of image
//   height  number of pixels height of image

does this mean width = nx?

**Comment by darren-moore** [comment]
Good question, it's a bit confusing. `viewing_ray` defines image width in pixels while `Camera.width` is the picture plane width in world-space.
