### ISSUE TITLE
Solution outputs for json files

### ISSUE THREAD

**Issue by charlesvong** [dilevin/computer-graphics-ray-casting#23]
I noticed that we don't have any solution images for two-sphere-and-plane.json and inside-a-sphere.json in the images folder. I know that last year there was a fix branch with solution images for those files, but the repo structure seems to be different in that branch (there was no data folder). 

I was wondering whether the solution images in that fix branch are consistent with our assignment, and if not, whether or not we can be provided with the solution images for them

**Comment by charlesvong** [comment]
Checked with a TA, we can use the images in the fix branch as reference :)

**Comment by darren-moore** [comment]
Indeed, you can check against the .ppm files currently living in the branch here: https://github.com/dilevin/computer-graphics-ray-casting/tree/fix/images/output_images
