### ISSUE TITLE
Eigen dot and cross products

### ISSUE THREAD

**Issue by RaihanFaruque** [dilevin/computer-graphics-ray-casting#26]
If i have 3 Vector3d a,b and c,

i can do 
double d = (a - b).dot(a - c), doing 

Vector3d v = (a - b).cross(a - c) gives an error. Is this intended?

**Comment by darren-moore** [comment]
What is the error? Compile-time or run-time?

**Comment by RaihanFaruque** [comment]
compile time

**Comment by darren-moore** [comment]
Can you paste the error from the logs? Then we can work out the meaning together. Eigen errors can sometimes be tough to understand.

**Comment by RaihanFaruque** [comment]
This is the error I get:
CMakeFiles/raycasting.dir/src/Triangle.cpp.o: In function `Triangle::intersect(Ray const&, double, double&, Eigen::Matrix<double, 3, 1, 0, 3, 1>&) const':
Triangle.cpp:(.text+0x175): undefined reference to `Eigen::MatrixBase<Eigen::CwiseBinaryOp<Eigen::internal::scalar_difference_op<double>, Eigen::Matrix<double, 3, 1, 0, 3, 1> const, Eigen::Matrix<double, 3, 1, 0, 3, 1> const> >::cross_product_return_type<Eigen::CwiseBinaryOp<Eigen::internal::scalar_difference_op<double>, Eigen::Matrix<double, 3, 1, 0, 3, 1> const, Eigen::Matrix<double, 3, 1, 0, 3, 1> const> >::type Eigen::MatrixBase<Eigen::CwiseBinaryOp<Eigen::internal::scalar_difference_op<double>, Eigen::Matrix<double, 3, 1, 0, 3, 1> const, Eigen::Matrix<double, 3, 1, 0, 3, 1> const> >::cross<Eigen::CwiseBinaryOp<Eigen::internal::scalar_difference_op<double>, Eigen::Matrix<double, 3, 1, 0, 3, 1> const, Eigen::Matrix<double, 3, 1, 0, 3, 1> const> >(Eigen::MatrixBase<Eigen::CwiseBinaryOp<Eigen::internal::scalar_difference_op<double>, Eigen::Matrix<double, 3, 1, 0, 3, 1> const, Eigen::Matrix<double, 3, 1, 0, 3, 1> const> > const&) const'

**Comment by dilevin** [comment]
I believe you need to include Eigen/Geometry (https://eigen.tuxfamily.org/dox/group__Geometry__Module.html) to get .cross to work correctly.

**Comment by RaihanFaruque** [comment]
After I included Eigen/Geometry, it works. Thank you
