### ISSUE TITLE
Eigen Matrix and Vector

### ISSUE THREAD

**Issue by IPexhausted** [dilevin/computer-graphics-ray-casting#28]
As TA Darren discussed in today's tutorial, he mentioned using A.colPivHouseholderQr().solve(b) to solve for triangle parameters.
I have a problem with how to put vector values(triangle corner) into Matrix(A)? Can someone help with this issue?

**Comment by darren-moore** [comment]
Indeed, we discussed that the triangle intersection test does a change of coordinates, and this requires a linear system solve. [This page](https://eigen.tuxfamily.org/dox/group__TutorialLinearAlgebra.html) is useful to see how Eigen can solve these.

See the textbook p78 or the lecture slides for how to set up the linear system, mathematically.
To initialize the Eigen matrix or for general Eigen functionality, you may find [this page](https://eigen.tuxfamily.org/dox/group__QuickRefPage.html) useful.

The following is a straightforward way to build a matrix.
```
Eigen::Matrix3d A;
lhs << col1, col2, col3;
```
