### ISSUE TITLE
Download Eigen

### ISSUE THREAD

**Issue by yeqingxi** [dilevin/computer-graphics-ray-casting#3]
I'm currently using the CDF machines, I get this error when i try to "make" the project:

"In file included from /h/u12/c6/00/yeqingxi/csc418/computer-graphics-ray-casting/include/TriangleSoup.h:4:0,
 from /h/u12/c6/00/yeqingxi/csc418/computer-graphics-ray-casting/src/TriangleSoup.cpp:1:
/h/u12/c6/00/yeqingxi/csc418/computer-graphics-ray-casting/include/Object.h:4:22: fatal error: Eigen/Core: No such file or directory"

Are we supposed to download Eigen by ourselves? If so, could someone provide a link to how?

**Comment by dilevin** [comment]
Eigen should be pulled down if you use the correct GitHub command. Can you detail exactly how you checked out the code ?

**Comment by yeqingxi** [comment]
Oh I see, the checkout was taking a long time so i think i terminated the process prematurely since I thought everything was pulled already. I will checkout again, thank you!

**Comment by jritch** [comment]
Hi, for everyone who sees this issue, cloning the repository will take a long time (> 10 min) when running on the CDF machines. However, it should eventually complete correctly.

This issue should be fixed in future assignments, though A3 may have the same problem.
