### ISSUE TITLE
Clarification on first_hit

### ISSUE THREAD

**Issue by ginkxo** [dilevin/computer-graphics-ray-casting#30]
The first_hit works on a vector of Objects. Are we correct to assume that for an arbitrary object in the vector array we can call the generic .intersect method for the arbitrary object (with the expectation that we later fill in each intersect for the respective Object type e.g. Sphere, Triangle, etc?) 

Thank you!

**Comment by darren-moore** [comment]
Indeed, `Object` has `intersect` as a virtual function that the derived classes like `Sphere` override.
(if interested: this polymorphism is often implemented with "[vtables](https://en.wikipedia.org/wiki/Virtual_method_table)")

**Comment by mathur15** [comment]
In terms of what first hit means does it mean the closest object in the scene, meaning the lowest t value? Apologies for the confusion.

**Comment by charlesvong** [comment]
yes it's the lowest t value that's still above the minimum depth view of the camera
