### ISSUE TITLE
Intersection with spheres: only one x greater than min_t?

### ISSUE THREAD

**Issue by BlackSpade741** [dilevin/computer-graphics-ray-casting#32]
I think this was mentioned in the lecture, but just making sure: If there are two solutions to the equation, but only one is greater than min_t, do we still say there is a hit, or do we ignore the hit as we are inside the sphere?

**Comment by dilevin** [comment]
one way to think about this is to ask if you were standing inside a sphere ... would you expect to see the inside wall ?
