### ISSUE TITLE
Could the fix branch be updated to include ppm output images for bunny?

### ISSUE THREAD

**Issue by MarcusTan** [dilevin/computer-graphics-ray-casting#33]
The [fix branch](https://github.com/dilevin/computer-graphics-ray-casting/tree/fix/images/output_images
) provides reference outputs for all json files in data, except bunny.

I understand that we already have a reference bunny.gif, but I would prefer some lossless image format :)

**Comment by darren-moore** [comment]
Good idea. I want to do some additional investigation into the flipped bunny issues that people are having first. Will post a reference output by tomorrow morning.

**Comment by darren-moore** [comment]
🐰🐇🐰 Images uploaded. Commit: https://github.com/dilevin/computer-graphics-ray-casting/commit/0becd8bf18d47927f78d945388a24b15232ed53f
