### ISSUE TITLE
Surface normals and Plane "q" 

### ISSUE THREAD

**Issue by ginkxo** [dilevin/computer-graphics-ray-casting#34]
1. We have to calculate the normal n for a sphere. For a plane and a triangle (in a sense a special kind of plane), does our given n for the plane (as an attribute of the Plane object) count as the surface normal to return automatically, or do we need to re-calculate the surface normal for the plane somehow? I assume we need to manually calculate the surface normal for the triangle given the 3 points? 

2. Would someone be able to clarify what "q" is in slide 40 of the Ray Casting lecture with the plane equations? Is it the distance between the given Plane point p1 and the ray origin "e"? 

Thank you!

**Comment by darren-moore** [comment]
1. As you observed, the Plane's normal is provided, but the Triangle's normal must be calculated.
2. `q` isn't explicitly defined, but you should be able to see that `q = n^T p_1` on p40. It's not the distance you described, but I don't see an obvious "real-world description" for `q`.
