### ISSUE TITLE
Understanding intersection for triangle

### ISSUE THREAD

**Issue by mathur15** [dilevin/computer-graphics-ray-casting#35]
I was hoping to seek some clarification on the intersection of the ray wrt to a triangle. As I understand it, it is a special case of a plane. So far, in my implementation, I have calculated the normal to the plane but taking a cross product of the two sides of the triangle. In order to determine t, I use the same formula as we have for the plane, however, in order to determine where the point lies on the triangle, 
I am trying to use p = alpha * A + beta * B +gamma* C, where p can be the point we found. I wanted to know **how we can calculate the values for alpha,beta,gamma since those are the constraints we have to check.** 

Thanks!

**Comment by dilevin** [comment]
ray-triangle intersection is explained in detail in the lecture 2 slides.
