### ISSUE TITLE
Inconsistencies between slides and code

### ISSUE THREAD

**Issue by JeremySant** [dilevin/computer-graphics-ray-casting#4]
I noticed some inconsistencies between the equations in the slides and the code. First that `i` and `j` are swapped in the code when compared to the slides (e.g. `i` is the variable for the width in the slides but in he code `i` is the variable for the height). I also noticed when I followed the equations in the slides for finding u and v my images rendered upside down. I am not 100% sure if this is a problem with the code or if I am doing something wrong, but I am able to fix it by flipping the v vector. Is this okay to do as long as the output is rendered correctly?

**Comment by dilevin** [comment]
You don’t have to use the equations verbatim from the notes. The images should render correctly. The principles behind the equations should be preserved but not their exact form.

**Comment by bod11** [comment]
I still think this is super confusing. Shouldn't the code be consistent with what we are learning in class? Also the ordering of i and j in declaration, and the fact they are i and j, suggest i is width and j is height. I might be wrong but isn't this typically convention?
