### ISSUE TITLE
Inside Spheres

### ISSUE THREAD

**Issue by ginkxo** [dilevin/computer-graphics-ray-casting#42]
I'm getting a peculiar situation where, in drawing inside-sphere, everything except the actual inside of the sphere draws. Example:

<img width="219" alt="insphere2" src="https://user-images.githubusercontent.com/21148289/72996862-6a568f80-3dc9-11ea-945a-58d42988bd33.png">

I suspect this might be due to how I return t values for Spheres. However, between a potential t1 and t2 ('entry' and 'exit' points) I generally always return the smaller of the two that is still greater than min_t -- is this a problem for considering how a ray would hit the inside of the sphere? Based off of the heuristic in the textbook for multiple objects, it appears even with this "smaller t" chosen, the Plane t appears to be even smaller, so would it make a difference?

**Comment by darren-moore** [comment]
Recall there are 3 cases for sphere intersection. 0 hits, 1 hit, and 2 hits. Are you handling all these cases?

**Comment by darren-moore** [comment]
I recommend drawing a picture with the image plane, camera, and sphere for this scene.

**Comment by ginkxo** [comment]
I believe so. In the 1 hit case where the ray "grazes" the sphere we have t1 = t2 so I set t1 and return true. I divide the 2 hit case, t1 =/= t2, into two separate cases, where I check which of these two t's are smaller while still being greater than min_t, set that one, return true. For the 0 hit case I simply return false.

 I know the 2 hit case situation & returning the smaller of the t's will likely return just the outside surfaces of the spheres only, but I am wondering then if this means that the 2 hit case likely needs more than just these two subcases to deal with situations where the inside of the sphere hits?

**Comment by darren-moore** [comment]
Ah sorry, you already said that in your original post. You seem to understand the nuance behind the 2 hit case involving min_t. Double check your greater-thans and less-thans, etc. I suspect a simple mistake.

**Comment by ginkxo** [comment]
it turns out I wasn't taking into account situations with the relationship between the t values and min_t properly, thanks very much for your help!
