### ISSUE TITLE
Images rotated on their side?

### ISSUE THREAD

**Issue by BlackSpade741** [dilevin/computer-graphics-ray-casting#43]
I'm encountering a weird problem where the image seems to be on its side and not displaying the whole thing. I'm using the formulas in the slides and the textbook to calculate viewing rays, what could the problem be?
![image](https://user-images.githubusercontent.com/24865967/73001206-13a08400-3dd0-11ea-8661-306aa54a9b1d.png)

**Comment by darren-moore** [comment]
It looks like your `i` and `j` indexing could be flipped. You may have to make some small modifications to the formulas. See https://github.com/dilevin/computer-graphics-ray-casting/issues/4 for example.
