### ISSUE TITLE
Clarification on the purpose of min_t

### ISSUE THREAD

**Issue by pjsmith97** [dilevin/computer-graphics-ray-casting#45]
Can I get a clarification of what exactly min_t is for? I suspect that my depth image relies on it since the plane doesn't look faded like the sample image suggests.

**Comment by darren-moore** [comment]
See the header files, in particular `first_hit.h` for more documentation.
```
min_t  minimum t value to consider (for viewing rays, this is typically at
least the _parametric_ distance of the image plane to the camera)
```

If you open `main.cpp` to see how the images are generated, you'll see that depth uses the outputted `t` to scale the colour. I suspect that even if your plane intersection test is correct, the `t` you output is incorrect.

**Comment by pjsmith97** [comment]
Okay...but are you saying that I should only be considering t's greater than or equal to min_t? Because when I do that, the plane isn't found at all. Like when I debug, t is never greater than 1 (which is the min_t) when it comes to the plane. My sphere's work so I don't expect it to be the ray.

**Comment by darren-moore** [comment]
What are some values of `t` that you're getting? My best guess is that you have a sign error. https://github.com/dilevin/computer-graphics-ray-casting/issues/36 may be useful.

**Comment by pjsmith97** [comment]
The first hit I get on the plane is around -2252.

**Comment by pjsmith97** [comment]
Also, in a simpler range, the numerator of the t formula I have is -1.

**Comment by darren-moore** [comment]
Indeed, the depth image is displaying a solid colour because you're sending those strange negative values to it.
Double check that your viewing rays aren't upside down. You might consider if the normal shading on the sphere is correct, or upside down.

**Comment by pjsmith97** [comment]
My image was on it's side before so I already fixed the mix up between i and j when I create the ray. And from my understanding (s-e) in the ray equation is it's normalized direction, so that is what I'm using in the denominator with it's dot product to the plane's normal. The shading of the sphere is off and now looking at it it does look upside down.

Am I also meant to normalize the camera origin? That's the only change I can think to make with my ray. I'm using the formula from the slides that has us use -d dot w. So I don't know where I'm going wrong here.

**Comment by darren-moore** [comment]
Camera origin is a position- consider what would happen if you normalized that. (hint: don't do it here!)

If the images are upside down, you should be investigating how you're using the camera basis. Draw a picture of how you're using the camera basis to make the image plane and think about what you need to flip in order to flip an image.

**Comment by pjsmith97** [comment]
The other images aren't upside though. The plane is the right orientation. I think my normal shader is just wrong in another sense.

But the only negatives are coming from my numerator, which has nothing to do with my ray save for the origin. I flipped that calculation and now my depth image is right for sphere and plane. But I was following the formula shown in lecture, so now it's (nT dot e - q). So what happened?

**Comment by darren-moore** [comment]
It's hard to know without more context, but try deriving the plane intersection equation by hand. (shouldn't be hard to do) And see the lecture slide mix up I mentioned earlier: https://github.com/dilevin/computer-graphics-ray-casting/issues/36

**Comment by pjsmith97** [comment]
Thank you, although I already saw the mix up post. Unless it's saying that I'm supposed to be using the negative of the ray's direction, I'm pretty sure it doesn't apply to me since I've only been using ray.direction in my code and not expanding it out to s and e.
