### ISSUE TITLE
Sphere Normal Shader Flipped

### ISSUE THREAD

**Issue by pjsmith97** [dilevin/computer-graphics-ray-casting#47]
In my normal shading, the sphere's normal shader is flipped. I'm using the method of finding it's normal by subtracting the center of the circle from the point of intersection (e + t*direction) and then dividing it by the radius. This is the closest I've gotten to the sample image. As you can see the plane normal is correct so it has something to do with my circle's normal.
![normal](https://user-images.githubusercontent.com/48391420/73097689-c0086600-3eb5-11ea-800f-e361d0bcbbb7.png)
For ease of reference this is what it's supposed to look like.
![sphere-and-plane-normal](https://user-images.githubusercontent.com/48391420/73098359-39548880-3eb7-11ea-89df-f574a948eb69.png)

**Comment by pjsmith97** [comment]
For ease of reference this is what it's supposed to look like.
![sphere-and-plane-normal](https://user-images.githubusercontent.com/48391420/73097960-618fb780-3eb6-11ea-9bb0-818f60770443.png)

**Comment by darren-moore** [comment]
It's possible that you have two problems: (1) image plane is flipped and (2) the plane intersection is flipped.

**Comment by pjsmith97** [comment]
If the image plane is flipped, where should the problem lie?

**Comment by darren-moore** [comment]
The image plane is defined by the `Camera`(given), which you use to create your `viewing_ray`s.
