### ISSUE TITLE
Expected output of inside-a-sphere.json

### ISSUE THREAD

**Issue by JeremySant** [dilevin/computer-graphics-ray-casting#5]
I was wondering if we were supposed to display rays that intersect with inside of the sphere as in this image:
![image](https://user-images.githubusercontent.com/9597842/51421298-50f18680-1b6a-11e9-8778-168deb0f23e1.png)

Or if we are only supposed to display rays that intersect with the outside of the sphere as in this image:

![image](https://user-images.githubusercontent.com/9597842/51421315-8a29f680-1b6a-11e9-9be0-446c79b151c2.png)

**Comment by dilevin** [comment]
The desired output, whether it be ID, normal or depth should match the images in the readme.

**Comment by Mincelot** [comment]
But the readme only have the sample output for some scenes which doesn't include the scene mentioned above (inside-a-sphere), is it possible for us to get the sample output for all the scenes?

**Comment by jritch** [comment]
Hi @Mincelot @JeremySant - please see the reference images for all scenes, added in commit 301399a.

Hopefully these clarify what the desired output is. 

https://github.com/dilevin/computer-graphics-ray-casting/tree/fix/images/output_images
