### ISSUE TITLE
Testing any triangle code

### ISSUE THREAD

**Issue by pjsmith97** [dilevin/computer-graphics-ray-casting#50]
How exactly do I go about testing Triangle.cpp. I've pulled from git and it says I'm already up to date if anything else has been added. Main.cpp only gives out the sphere code from what I see so far. I've heard that we're supposed to change the the json file but I looked and the file is so big and daunting I don't know where to start. I really need some assistance here.

**Comment by darren-moore** [comment]
Change the hard-coded path in `main.cpp` to generate different images: https://github.com/dilevin/computer-graphics-ray-casting/blob/9685043cf433bd4093cd4849a8d843d9ad3ec5b6/main.cpp#L36

**Comment by pjsmith97** [comment]
So if I only change "sphere-and-plane" to "sphere-packing", that should give me all of the tests for that file? I don't need to change anything else in that line?

**Comment by darren-moore** [comment]
Try it and see! (yes)
Look in the `data` folder for all the scenes we've provided.

**Comment by pjsmith97** [comment]
Okay thank you.
