### ISSUE TITLE
Finding t for Triangles

### ISSUE THREAD

**Issue by pjsmith97** [dilevin/computer-graphics-ray-casting#51]
So two questions regarding this:

1) I'm assuming that we are choosing our own alpha and beta so long as they fit within the parameters set in the slides (both >= zero and sum <= 1). Is this correct?

2) I'm confused on why for the intersection check that we're equating everything to e and not t. How exactly are we checking alpha, beta and t as the last slide indicates?

**Comment by darren-moore** [comment]
You may find the textbook a useful resource in addition to the slides.
1. Alpha and Beta are coordinates in the barycentric "triangle" coordinate system. These must be calculated. From another perspective: Any alpha and beta coordinates that satisfy the constraints you mentioned are within the triangle.
2. [alpha, beta, t]^T is the solutions to a linear system Ax=b. See https://github.com/dilevin/computer-graphics-ray-casting/issues/28

**Comment by pjsmith97** [comment]
Thanks
