### ISSUE TITLE
Viewing Ray u and v Textbook formula vs. Slides formula

### ISSUE THREAD

**Issue by pjsmith97** [dilevin/computer-graphics-ray-casting#52]
Up until now I understood the general u and v formulas to be what they are shown in the slides:

<img width="1099" alt="Screen Shot 2020-01-25 at 12 21 23 AM" src="https://user-images.githubusercontent.com/48391420/73116701-c70c9400-3f08-11ea-89d0-29580f679954.png">

However, after reading through the textbook section, I understand that the general formula is actually this:

<img width="696" alt="Screen Shot 2020-01-25 at 12 17 15 AM" src="https://user-images.githubusercontent.com/48391420/73116712-ec010700-3f08-11ea-9216-83c8a1b75455.png">

My question is are all the images we're using in the assignment following the format shown in the slides (i.e. -0.5<v<3.5 and -0.5<u<3.5)? If not, how do we find the bounds?

**Comment by darren-moore** [comment]
Does https://github.com/dilevin/computer-graphics-ray-casting/issues/19 answer your question?

**Comment by pjsmith97** [comment]
It does for this question, thank you
