### ISSUE TITLE
colors for normal images seem muted

### ISSUE THREAD

**Issue by chengk68** [dilevin/computer-graphics-ray-casting#59]
Hi! I just implemented sphere and ran it to check if anything would show...and im noticing the colors for my normal seem muted? Any idea what might be causing this?

![sphere2](https://github.com/dilevin/computer-graphics-ray-casting/assets/90589823/41a5c8fe-20d0-493e-8c75-f758b405d478)
![sphere1](https://github.com/dilevin/computer-graphics-ray-casting/assets/90589823/361f2f93-7cd1-4c28-96f6-ed9eed577ea0)

**Comment by ThatGenericName** [comment]
Have you checked to make sure the normals have been normalized?
