### ISSUE TITLE
cross product not found for architecture arm64

### ISSUE THREAD

**Issue by AndyKaySum** [dilevin/computer-graphics-ray-casting#62]
I'm using an apple silicon MacBook and I got this error trying to use get the cross product of 2 Vector3d values using cross().

<img width="1105" alt="Screenshot 2023-09-26 at 12 13 01 AM" src="https://github.com/dilevin/computer-graphics-ray-casting/assets/90937834/39a5d4d1-df90-43bd-9679-a7124ce1ba79">

**Comment by junseomoon9** [comment]
Try adding: #include <Eigen/Geometry> in your Triangle.cpp file

**Comment by evelyh** [comment]
I have x86-64, only got this error when I used the optimized compiler. The solution above works for me @junseomoon9 Thanks!

**Comment by AndyKaySum** [comment]
Worked for me, thanks!
