### ISSUE TITLE
Bunny is very slow to run

### ISSUE THREAD

**Issue by Anesthez** [dilevin/computer-graphics-ray-casting#75]
I implemented the triangle intersection by solving the matrix according to lecture notes, but when I run bunny.json it is extremely slow. It takes over 30 minutes to run for my mac. Does anyone have same issue?

**Comment by dilevin** [comment]
Make sure you compile your code in release mode (so in linux do "cmake .. -DCMAKE_BUILD_TYPE=Release" then recompile via the make file. This can make a huge performance difference.

**Comment by Anesthez** [comment]
thank you, solved
